swagger: '2.0'
info:
  version: '0.1'
  description: 'Acesta este interfata de comunicare cu operatorii de sisteme de furnizat bonuri de ordine'
  title: Stop Cozi API
  termsOfService: 'http://stopcozi.ithub.gov.ro/terms/'
  contact:
    email: 'api@gov.ro'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: stare
    description: Operatiune de stabilire a starii unei locatii
  - name: activitate
    description: Operatiuni de comunicare a operatiunilor legate de bonuri
schemes:
  - http
paths:
  '/agency/{agencyId}':
    put:
      tags:
        - stare
      summary: Actualizeaza agentia.
      operationId: updateAgency
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: agency
          in: body
          description: Starea agentiei
          required: true
          schema:
            $ref: '#/definitions/Agency'
      responses:
        '200':
          description: Agentia a fost actualizata
        '404':
          description: Agentie inexistenta
        '409':
          description: Informatii lipsa
  '/ticket/{agencyId}/{serviceId}/{ticketNo}':
    post:
      tags:
        - activitate
      summary: Creaza bon
      operationId: createTicket
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: agencyId
          in: path
          type: string
        - name: serviceId
          in: path
          type: string
        - name: ticketNo
          in: path
          type: string
        - name: ticket
          in: body
          schema:
            $ref: '#/definitions/Ticket'
          description: Continutul bonului
      responses:
        '200':
          description: Bonul a fost creat
    put:
      tags:
        - activitate
      summary: Actualizeaza (partial) bonul
      operationId: updateTicket
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: agencyId
          in: path
          type: string
        - name: serviceId
          in: path
          type: string
        - name: ticketNo
          in: path
          type: string
        - name: ticket
          in: body
          schema:
            $ref: '#/definitions/Ticket'
          description: Continutul bonului
      responses:
        '200':
          description: Bonul a fost actualizat
definitions:
  Agency:
    type: object
    required:
      - agencyId
      - services
      - desks
    properties:
      agencyId:
        type: string
        description: Id-ul agentiei (ca locatie fizica)
      agencyName:
        type: string
        description: numele scurt al agentiei (SPCRPCIV)
      location:
        type: string
        description: Locatia agentiei
      description:
        type: string
        description: Numele complet al agentiei
      categories:
        type: array
        items:
          $ref: '#/definitions/Category'
      services:
        type: array
        items:
          $ref: '#/definitions/Service'
      desks:
        type: array
        items:
          $ref: '#/definitions/Desk'
  Category:
    type: object
    required:
      - categoryId
    properties:
      categoryId:
        type: string
      categoryName:
        type: string
  Service:
    type: object
    required:
      - serviceId
      - workingHours
      - ticketsInProgress
      - lastIssuedTicket
    properties:
      serviceId:
        type: string
        description: Id-ul serviciului
      serviceName:
        type: string
        description: Numele serviciului
      categoryIds:
        type: array
        items:
          type: string
        description: Categorii asociate serviciului
      workingHours:
        type: array
        items:
          $ref: '#/definitions/ServiceSchedule'
        description: Programul serviciului
      ticketsInProgress:
        type: array
        items:
          type: string
        description: Numerele bonurilor aflate in lucru
      lastIssuedTicket:
        type: string
        description: Ultimul bon emis
      ticketLimit:
        type: integer
        format: int32
  Desk:
    type: object
    required:
      - deskId
    properties:
      deskId:
        type: string
      deskName:
        type: string
  Ticket:
    type: object
    required:
      - ticketNo
      - issueDate
      - status
      - serviceId
    properties:
      ticketNo:
        type: integer
        format: int32
      issueDate:
        type: number
        description: Data emiterii
        format: 'date-time'
      status:
        $ref: '#/definitions/TicketStatus'
      serviceId:
        type: string
        description: Serviciul de referinta
      deskId:
        type: string
        description: Ghiseul catre care a fost directionat bonul
  TicketStatus:
    type: string
    enum:
      - issued
      - in_progress
      - suspended
      - solved
    description: Stari posibile pentru un bon
  ServiceSchedule:
    type: object
    properties:
      start:
        type: string
        format: 'date-time'
        description: De la
      end:
        type: string
        format: 'date-time'
        description: Pana la
      desks:
        type: array
        items:
          type: string
        description: Ghiseele arondate